# Generated by Django 4.2.2 on 2023-06-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_user_cleaningservice_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="cleaningservice", name="duration",),
        migrations.RemoveField(model_name="cleaningservice", name="image",),
    ]
