# Generated by Django 4.2.2 on 2023-06-27 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_cleaningservice_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking", name="duration", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
