# Generated by Django 4.2.2 on 2023-06-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_img"),
    ]

    operations = [
        migrations.DeleteModel(name="Img",),
    ]
