# Generated by Django 4.2.2 on 2023-07-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_customuser"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
