# Generated by Django 4.2.2 on 2023-07-10 12:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_booking_time"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customer",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="booking", name="time", field=models.TimeField(default="12:24"),
        ),
    ]
