# Generated by Django 4.2.2 on 2023-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_customer_managers_alter_booking_time"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customer", managers=[],),
        migrations.AlterField(
            model_name="booking", name="time", field=models.TimeField(default="17:17"),
        ),
    ]
