# Generated by Django 4.2.2 on 2023-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_booking_customer_alter_booking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="time", field=models.TimeField(default="16:49"),
        ),
    ]
