# Generated by Django 4.2.2 on 2023-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_booking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="name", max_length=255),
        ),
        migrations.AlterField(
            model_name="booking", name="time", field=models.TimeField(default="20:35"),
        ),
    ]
