# Generated by Django 4.2.2 on 2023-07-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="time", field=models.TimeField(default="00:45"),
        ),
    ]
